#
#Should include and execute the makefile for the searchclient, as well as maketable,
#prober etc., as well as make clean for all of them, tidying up things
#
#
all: prober makeTable searchclient

default: all

prober:

makeTable:
